# Generated by Django 2.2.7 on 2019-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20191107_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
